#!/usr/bin/env bash
# heart-vb plugin installer for The Heart Vibe marketplace.
# Idempotent — bezpiecznie odpalać wielokrotnie.
# Installs council CLI dependencies (uv, gemini-cli, codex auth check).
# Other skills (self-improving, vb-*, heart-custom) są markdown — auto-loaded by Claude Code.

set -euo pipefail

VENV="${COUNCIL_VENV:-$HOME/tools/council-env}"
WRAPPER_DIR="${COUNCIL_WRAPPER_DIR:-$HOME/.local/bin}"
WRAPPER="$WRAPPER_DIR/council"

say() { printf '\033[1;34m▸\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m⚠\033[0m %s\n' "$*"; }
ok() { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Zależności systemowe ──────────────────────────────────────────────────
say "Sprawdzam zależności systemowe..."

if ! command -v uv >/dev/null 2>&1; then
  say "uv nie znaleziony — instaluję..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
  command -v uv >/dev/null 2>&1 || fail "Instalacja uv nieudana. Doinstaluj ręcznie: https://docs.astral.sh/uv/"
fi
ok "uv: $(uv --version)"

if ! command -v node >/dev/null 2>&1; then
  fail "Node.js wymagany dla Gemini CLI. Zainstaluj nodejs (brew install node lub nvm)."
fi
ok "node: $(node --version)"

if ! command -v gemini >/dev/null 2>&1; then
  say "Gemini CLI nie znaleziony — instaluję @google/gemini-cli globalnie..."
  npm install -g @google/gemini-cli
fi
ok "gemini: $(gemini --version 2>/dev/null || echo 'zainstalowany')"

# ── 2. Python venv + pakiet ──────────────────────────────────────────────────
say "Tworzę venv w $VENV..."
if [ ! -d "$VENV" ]; then
  uv venv "$VENV"
fi
say "Instaluję the-llm-council[gemini]..."
uv pip install --upgrade 'the-llm-council[gemini]>=0.7.16' --python "$VENV/bin/python" --quiet
ok "the-llm-council zainstalowany w $VENV"

# ── 3. Wrapper CLI ───────────────────────────────────────────────────────────
say "Tworzę wrapper $WRAPPER..."
mkdir -p "$WRAPPER_DIR"
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Wrapper auto-generated by council plugin install.sh
VENV="\${COUNCIL_VENV:-$VENV}"
if [ ! -x "\$VENV/bin/council" ]; then
  echo "ERROR: council not found at \$VENV/bin/council" >&2
  echo "Re-run installer: bash <(curl -s https://raw.githubusercontent.com/The-Heart-Vibe/the-heart-marketplace/main/plugins/heart-vb/install.sh)" >&2
  exit 1
fi
exec "\$VENV/bin/council" "\$@"
EOF
chmod +x "$WRAPPER"
ok "wrapper: $WRAPPER"

# ── 4. PATH check ────────────────────────────────────────────────────────────
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$WRAPPER_DIR"; then
  warn "$WRAPPER_DIR nie jest w \$PATH"
  warn "Dodaj do ~/.zshrc lub ~/.bashrc:"
  warn '  export PATH="$HOME/.local/bin:$PATH"'
  warn "Albo używaj pełnej ścieżki: $WRAPPER"
fi

# ── 5. Config template ───────────────────────────────────────────────────────
CONFIG_DIR="$HOME/.config/llm-council"
CONFIG_FILE="$CONFIG_DIR/config.yaml"
if [ ! -f "$CONFIG_FILE" ]; then
  say "Tworzę config $CONFIG_FILE..."
  mkdir -p "$CONFIG_DIR"
  cp "$(dirname "$0")/config/llm-council.example.yaml" "$CONFIG_FILE"
  ok "Config utworzony — edytuj $CONFIG_FILE jeśli chcesz custom defaults"
else
  ok "Config już istnieje: $CONFIG_FILE (zachowany)"
fi

# ── 6. Doctor ────────────────────────────────────────────────────────────────
say "Uruchamiam council doctor..."
echo ""
"$WRAPPER" doctor || true
echo ""

# ── 7. Hooks — auto-loaded przez Claude Code v2.1+ ────────────────────────────
# Plugin zawiera hooks/hooks.json — Claude Code (CLI + Cowork w Desktop) auto-loaduje
# hooki z tego pliku przy każdej sesji. NIE wpisujemy ręcznie do ~/.claude/settings.json
# bo to powoduje "duplicate hooks" error (PLUGIN_SCHEMA_NOTES.md) i NIE działa w Cowork
# (sandboxed per-session, nie czyta globalnego settings.json).
say "Hooki auto-loaded przez Claude Code z hooks/hooks.json (działa w CLI i Cowork)"
ok "vb-suggest, devtools-suggest, cowork-suggest, model-route — aktywne po restarcie sesji"

# ── 7b. Legacy cleanup — usuń stare wpisy w ~/.claude/settings.json ──────────
# Wcześniejsze wersje pluginu (do v0.6.9) instalowały hooki ręcznie. Trzeba je usunąć
# żeby uniknąć duplikatu (raz przez plugin auto-load + raz przez settings.json).
SETTINGS="$HOME/.claude/settings.json"
if [ -f "$SETTINGS" ]; then
  python3 <<'PYEOF' 2>/dev/null || true
import json, os, sys
settings_path = os.path.expanduser("~/.claude/settings.json")
legacy_markers = [
    "council-vb-suggest.sh",
    "heart-devtools-suggest.sh",
    "heart-cowork-suggest.sh",
    "heart-model-route.sh",
]
try:
    with open(settings_path) as f:
        cfg = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    sys.exit(0)

hooks_section = cfg.get("hooks", {}).get("UserPromptSubmit", [])
if not hooks_section:
    sys.exit(0)

# Filter out entries pointing to legacy heart-vb hooks
removed = 0
kept = []
for entry in hooks_section:
    is_legacy = any(
        any(marker in h.get("command", "") for marker in legacy_markers)
        for h in entry.get("hooks", [])
    )
    if is_legacy:
        removed += 1
    else:
        kept.append(entry)

if removed > 0:
    cfg["hooks"]["UserPromptSubmit"] = kept
    # Backup before write
    backup = f"{settings_path}.bak.cleanup.{os.popen('date +%Y%m%d-%H%M%S').read().strip()}"
    os.system(f"cp {settings_path} {backup}")
    with open(settings_path, "w") as f:
        json.dump(cfg, f, indent=2)
    print(f"  Usunięto {removed} legacy hook entries z ~/.claude/settings.json (backup: {backup})")
    print(f"  Stare pliki ~/.claude/hooks/heart-*.sh / council-vb-suggest.sh można teraz usunąć ręcznie")
PYEOF
fi

# ── 8. Codex CLI hint (opcjonalny, dla full Pattern F) ──────────────────────
echo ""
if ! command -v codex >/dev/null 2>&1; then
  say "Codex CLI — opcjonalny dla full Pattern F multi-LLM debate (3 LLMs)"
  cat <<EOF

   Bez Codex Pattern F działa jako 2-voice (Claude + Gemini) — w 90% przypadków wystarczy.
   Pełny 3-voice (Claude + Gemini + GPT-5) wymaga ChatGPT Plus + Codex CLI:

   1. Wymagana subskrypcja ChatGPT Plus (€22/mo): https://chatgpt.com
   2. Install Codex CLI (zewnętrzne narzędzie OpenAI — patrz dokumentacja Codex)
   3. Login: \`codex login\` (browser OAuth z ChatGPT)
   4. Verify: \`~/.local/bin/council doctor\` → codex powinien być OK

   Plugin DZIAŁA bez Codex — analityk dostaje Pattern F 2-voice fallback automatycznie.
EOF
else
  ok "Codex CLI wykryty: $(codex --version 2>/dev/null | head -1 || echo 'available')"
  if ! ~/.local/bin/council doctor 2>&1 | grep -q "codex.*OK"; then
    warn "Codex CLI zainstalowany ALE nie zalogowany — login: \`codex login\` (ChatGPT Plus required)"
    warn "Bez login: Pattern F będzie pomijać codex worker (graceful degradation = 2-voice)"
  fi
fi

# ── 9. Chrome DevTools MCP — VERIFY (od v0.7.4 auto-installed by plugin.json mcpServers) ────────
echo ""
say "Chrome DevTools MCP — sprawdzam status (od v0.7.4 auto-installed przez /plugin install)"
DEVTOOLS_INSTALLED="no"
if command -v claude >/dev/null 2>&1; then
  if claude mcp list 2>/dev/null | grep -qi "chrome-devtools"; then
    DEVTOOLS_INSTALLED="yes"
  fi
fi
# Fallback: check configs (legacy path)
if [ "$DEVTOOLS_INSTALLED" = "no" ]; then
  for cfg in "$HOME/.claude.json" "$HOME/.claude/mcp.json" "$HOME/.config/claude/mcp.json"; do
    if [ -f "$cfg" ] && grep -qi "chrome-devtools" "$cfg" 2>/dev/null; then
      DEVTOOLS_INSTALLED="yes"
      break
    fi
  done
fi

if [ "$DEVTOOLS_INSTALLED" = "yes" ]; then
  ok "chrome-devtools-mcp wykryty — devtools-suggest hook ma czego potrzebuje"
else
  say "Plugin spec deklaruje chrome-devtools w mcpServers — powinno być auto-installed przy /plugin install."
  say "Jeśli brak — fallback: install manually..."
  if command -v claude >/dev/null 2>&1; then
    # Fallback dla pre-v0.7.4 setups lub jeśli mcpServers auto-install nie zadziałał
    if claude mcp add --scope user chrome-devtools npx chrome-devtools-mcp@latest 2>/dev/null \
       || claude mcp add chrome-devtools npx chrome-devtools-mcp@latest 2>/dev/null; then
      ok "chrome-devtools-mcp zainstalowany via \`claude mcp add\` (manual fallback)"
      ok "Restart Claude Code aby nowy MCP server był aktywny w aktualnej sesji"
    else
      warn "Auto-install nie powiódł się — uruchom ręcznie:"
      warn "  claude mcp add chrome-devtools npx chrome-devtools-mcp@latest"
      warn "Plugin DZIAŁA bez tego — hook fallbackuje na WebFetch automatycznie."
    fi
  else
    warn "\`claude\` CLI nie znalezione — nie mogę zainstalować chrome-devtools-mcp automatycznie."
    warn "Po doinstalowaniu Claude Code, uruchom ręcznie:"
    warn "  claude mcp add chrome-devtools npx chrome-devtools-mcp@latest"
    warn "Plugin DZIAŁA bez tego — hook fallbackuje na WebFetch automatycznie."
  fi
fi

# ── 10. Next steps ───────────────────────────────────────────────────────────
cat <<EOF

──────────────────────────────────────────────────────────────────
✓ Council zainstalowany!
──────────────────────────────────────────────────────────────────

Auth dla providerów (sprawdź wyżej w doctor):

  claude     →  Powinien być OK (Claude Code już zalogowany)
                ❌ NIE DZIAŁA z poziomu aktywnej Claude Code session
  codex      →  Jeśli FAIL: \`codex login\` (wymaga ChatGPT Plus/Pro). OPCJONALNE — Pattern F bez tego = 2-voice fallback.
  gemini-cli →  Jeśli FAIL: \`gemini\` (OAuth przez Google Workspace)

Następnie w Claude Code:
  /plugin install heart-vb@the-heart-marketplace   # jeśli nie zrobiłeś jeszcze
  /council <twoje pytanie>

Lub bezpośrednio z terminala:
  council run planner --mode assess "Twoja decyzja" \\
    --providers gemini-cli,codex --json

Jeśli włączyłeś hook — przy okazji każdej decyzji-podobnej wiadomości
Claude zapyta "uruchomić przez /council?". Możesz opt-out per-wiadomość:
  BEZ COUNCIL: jak działa SSE?
EOF
